[2025-01-08T13:32:09.098+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.preprocess_to_staging scheduled__2025-01-07T00:00:00+00:00 [queued]>
[2025-01-08T13:32:09.105+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.preprocess_to_staging scheduled__2025-01-07T00:00:00+00:00 [queued]>
[2025-01-08T13:32:09.106+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:32:09.114+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): preprocess_to_staging> on 2025-01-07 00:00:00+00:00
[2025-01-08T13:32:09.117+0000] {standard_task_runner.py:57} INFO - Started process 602 to run task
[2025-01-08T13:32:09.120+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'preprocess_to_staging', 'scheduled__2025-01-07T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp73q69spn']
[2025-01-08T13:32:09.123+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask preprocess_to_staging
[2025-01-08T13:32:09.135+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:32:09.166+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.preprocess_to_staging scheduled__2025-01-07T00:00:00+00:00 [running]> on host 8105279881a3
[2025-01-08T13:32:09.250+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-07T00:00:00+00:00'
[2025-01-08T13:32:09.258+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:32:09.258+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/scripts/preprocess_to_staging.py --bucket_raw raw --db_host mysql --db_user root --db_password root --endpoint-url http://localstack:4566']
[2025-01-08T13:32:09.267+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:32:10.792+0000] {subprocess.py:93} INFO - Récupération des données depuis le bucket raw...
[2025-01-08T13:32:10.796+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données depuis S3: Unable to locate credentials
[2025-01-08T13:32:10.916+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:32:10.965+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=preprocess_to_staging, execution_date=20250107T000000, start_date=20250108T133209, end_date=20250108T133210
[2025-01-08T13:32:10.990+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:32:11.015+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
